import type { ApiVariant } from './api-definitions'

const HEADERS_WITH_KEY = `Content-Type : "application/json"\nx-karza-key: "<<YOUR KEY HERE>>"`
const HEADERS_JSON_ONLY = `Content-Type : "application/json"`

const DEFAULT: ApiVariant = {
  label: "Driver's License authentication",
  request: {
    params: [
      { name: 'consent', in: 'body', required: true, type: 'string', enum: ['Y', 'N'], description: 'Consent is required to make the API request.' },
      { name: 'dlNo', in: 'body', required: true, type: 'string', uppercase: true, placeholder: 'MH0120130001960', description: "Driving License Number as mentioned on the license including special characters and spaces.", example: 'minLength: 9 maxLength: 50' },
      { name: 'dob', in: 'body', required: true, type: 'string', placeholder: 'DD-MM-YYYY', description: 'Date of Birth as per License in dd-mm-yyyy format', example: '01-01-1900 to current date, pattern: ^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-(19|20)\\d\\d$' },
      { name: 'additionalDetails', in: 'body', required: false, type: 'boolean', description: 'If this is true, it will return endorsement and hazardous details', example: 'True or False' },
      { name: 'clientData', in: 'body', required: false, type: 'object', description: 'Data of the user sharing consent' },
      { name: 'clientData.caseId', in: 'body', required: false, type: 'string', description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
    ],
    body: JSON.stringify({
      dlNo: 'MH0120130001960',
      dob: '05-10-1994',
      additionalDetails: true,
      consent: 'Y',
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'requestId', type: 'string', required: true, description: 'Unique id of the API request.' },
      { field: 'result', type: 'object', required: false, description: 'Response object for the given inputs.' },
      { field: 'result.issueDate', type: 'string', required: false, description: 'Date of Issue of the Driving License in dd-mm-yyyy format' },
      { field: 'result.father/husband', type: 'string', required: false, description: 'Name of Relative' },
      { field: 'result.name', type: 'string', required: false, description: 'Owner Name as per Driving License' },
      { field: 'result.img', type: 'string', required: false, description: 'Image of the licence holder' },
      { field: 'result.bloodGroup', type: 'string', required: false, description: 'Blood Group of the owner' },
      { field: 'result.dob', type: 'string', required: false, description: 'Date of Birth of the owner in dd-mm-yyyy format' },
      { field: 'result.dlNumber', type: 'string', required: false, description: 'Driving License Number of the owner' },
      { field: 'result.validity', type: 'object', required: false, description: 'Validity of the license as per purpose of driving — transport or non-transport' },
      { field: 'result.validity.nonTransport', type: 'string', required: false, description: 'Validity of the license for non-transport ("dd-mm-yyyy to dd-mm-yyyy" or "dd-mm-yyyy" or "" or null)' },
      { field: 'result.validity.transport', type: 'string', required: false, description: 'Validity of the license for transport ("dd-mm-yyyy to dd-mm-yyyy" or "dd-mm-yyyy" or "" or null)' },
      { field: 'result.covDetails', type: 'array', required: false, description: 'Category of Vehicles the licensee is authorized to drive along with effective date' },
      { field: 'result.covDetails[].cov', type: 'string', required: false, description: 'Category of vehicle (LMV, HMV, HPMV, etc.)' },
      { field: 'result.covDetails[].issueDate', type: 'string', required: false, description: 'Date of Issue of the license or place where the license has been issued in dd-mm-yyyy format' },
      { field: 'result.address', type: 'array', required: false, description: 'Registered addresses as per Driving License' },
      { field: 'result.address[].addressLine1', type: 'string', required: false, description: 'Address Line 1' },
      { field: 'result.address[].state', type: 'string', required: false, description: 'State' },
      { field: 'result.address[].district', type: 'string', required: false, description: 'District' },
      { field: 'result.address[].pin', type: 'integer', required: false, description: 'Pin Code' },
      { field: 'result.address[].completeAddress', type: 'string', required: false, description: 'Complete Address' },
      { field: 'result.address[].country', type: 'string', required: false, description: 'Country' },
      { field: 'result.address[].type', type: 'string', required: false, description: 'Address Type (Present/Permanent/NA)' },
      { field: 'result.status', type: 'string', required: false, description: 'Status of the Driving License Number as per Government Records' },
      { field: 'result.statusDetails', type: 'object', required: false, description: 'Details of the Driving License Status' },
      { field: 'result.statusDetails.from', type: 'string', required: false, description: 'Driving License valid from date in dd-mm-yyyy format' },
      { field: 'result.statusDetails.to', type: 'string', required: false, description: 'Driving License valid to date in dd-mm-yyyy format' },
      { field: 'result.statusDetails.remarks', type: 'string', required: false, description: 'Remarks for the Status' },
      { field: 'result.endorsementAndHazardousDetails', type: 'object', required: false, description: 'Details of Endorsement and Hazardous Validity' },
      { field: 'result.endorsementAndHazardousDetails.initialIssuingOffice', type: 'string', required: false, description: 'Initial Issuing RTO for given Driving License' },
      { field: 'result.endorsementAndHazardousDetails.lastEndorsementDate', type: 'string', required: false, description: 'Latest endorsement date if any act was imposed on Driving License owner in dd-mm-yyyy format' },
      { field: 'result.endorsementAndHazardousDetails.lastEndorsedOffice', type: 'string', required: false, description: 'Lastest RTO who imposed the endorsement on Driving License owner' },
      { field: 'result.endorsementAndHazardousDetails.endorsementReason', type: 'string', required: false, description: 'Detailed Reason of endorsement' },
      { field: 'result.endorsementAndHazardousDetails.hazardousValidTill', type: 'string', required: false, description: 'Date of validity to drive hazardous vehicle' },
      { field: 'result.endorsementAndHazardousDetails.hillValidTill', type: 'string', required: false, description: 'Date of validity to drive vehicle in hill roads' },
      { field: 'clientData', type: 'object', required: true, description: 'Data of the user sharing consent' },
      { field: 'clientData.caseId', type: 'string', required: true, description: 'Unique case id/lead id of the user sharing consent' },
    ],
    body: JSON.stringify({
      requestId: 'ef484b85-34b9-45cb-99de-119accb91066',
      result: {
        issueDate: '08-01-2013',
        'father/husband': 'DIVAKAR PANDEY',
        name: 'PUNEET PANDEY',
        img: '/9j/4AAQSkZJRgABAQAAAQABAAD...',
        bloodGroup: 'B+',
        dob: '05-10-1994',
        dlNumber: 'MH0120130001960',
        validity: { nonTransport: '08-01-2013 to 07-01-2033', transport: '' },
        covDetails: [
          { cov: 'MCWG', issueDate: '08-01-2013' },
          { cov: 'LMV', issueDate: '08-01-2013' },
        ],
        address: [
          {
            addressLine1: '',
            state: 'MAHARASHTRA',
            district: 'MUMBAI',
            pin: 400013,
            completeAddress: 'C/304 PIMPLESHWAR CHS MAHADEV PALAV MARG CURREY RD MUMBAI MUMBAI,MUMBAI,MH 400013',
            country: '',
            type: 'NA',
          },
        ],
        status: 'Active',
        statusDetails: { from: '', to: '', remarks: '' },
        endorsementAndHazardousDetails: {
          initialIssuingOffice: 'RTO,MUMBAI CENTRAL',
          lastEndorsementDate: '02-01-2018',
          lastEndorsedOffice: 'RTO,MUMBAI CENTRAL',
          endorsementReason: 'ISSUE OF DUPLICATE DL , ISSUE OF DRIVING LICENCE',
          hazardousValidTill: 'NA',
          hillValidTill: 'NA',
        },
      },
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

export const DL_VARIANTS: ApiVariant[] = [DEFAULT]
