// PAN Profile (Detailed) — copied verbatim from the TotalKYC vendor docs
// (External API/Documentation … pan_profile.pdf). Three request/response
// variants: Default, "PAN Lite Details", "Father Name". Response field paths
// encode nesting (result.address.city) so the schema table renders the tree.

import type { ApiVariant } from './api-definitions'

const HEADERS_WITH_KEY = `Content-Type : "application/json"\nx-karza-key: "<<YOUR KEY HERE>>"`
const HEADERS_JSON_ONLY = `Content-Type : "application/json"`

// ── Shared response subtrees (identical across Default & Father Name) ──────────
// Address block under a given parent path.
function addressFields(parent: string) {
  return [
    { field: `${parent}.buildingName`, type: 'string', required: false, description: 'House Number/Building details' },
    { field: `${parent}.locality`,     type: 'string', required: false, description: 'Address Locality' },
    { field: `${parent}.streetName`,   type: 'string', required: false, description: 'Street Location as on the Address' },
    { field: `${parent}.pinCode`,      type: 'string', required: false, description: 'Pincode as on the Address' },
    { field: `${parent}.city`,         type: 'string', required: false, description: 'City as on the Address' },
    { field: `${parent}.state`,        type: 'string', required: false, description: 'State as on the Address' },
    { field: `${parent}.country`,      type: 'string', required: false, description: 'Country as on the Address' },
  ]
}

// ── Default variant ───────────────────────────────────────────────────────────

const DEFAULT: ApiVariant = {
  label: 'Full profile',
  request: {
    params: [
      { name: 'consent',          in: 'body', required: true,  type: 'string', description: 'Consent is required to make the API request.', enum: ['Y', 'N'] },
      { name: 'pan',              in: 'body', required: true,  type: 'string', label: 'PAN Number', uppercase: true, placeholder: 'ABCDE1234F', description: 'PAN of the Individual/Entity', example: 'minLength: 10 maxLength: 10 pattern: ^[A-Za-z]{5}\\d{4}[A-Za-z]{1}$' },
      { name: 'aadhaarLastFour',  in: 'body', required: false, type: 'string', description: 'Last 4 digits of the Aadhaar No (applicable only for individual PAN)', example: 'minLength: 4 maxLength: 4' },
      { name: 'dob',             in: 'body', required: false, type: 'string', label: 'Date of Birth', placeholder: 'YYYY-MM-DD', description: 'Date of Birth/Incorporation for the Individual/Entity', example: 'YYYY-MM-DD' },
      { name: 'name',            in: 'body', required: false, type: 'string', description: 'Name to be matched with the response for the Individual/Entity' },
      { name: 'address',         in: 'body', required: false, type: 'string', description: 'Address to be matched with the response for the Individual/Entity' },
      { name: 'getContactDetails', in: 'body', required: false, type: 'string', description: 'If this is yes, it will return email and contact number', enum: ['Y', 'N'] },
      { name: 'PANStatus',       in: 'body', required: false, type: 'string', description: 'If this is yes, it will return PAN status and PAN issue date', enum: ['Y', 'N'] },
      { name: 'isSalaried',      in: 'body', required: false, type: 'string', description: 'If this is yes, it will check whether given PAN belongs to a salaried individual. Please Note - This flag will only be applicable for Individual PAN', enum: ['Y', 'N'] },
      { name: 'isDirector',      in: 'body', required: false, type: 'string', description: 'If this is yes, it will whether given PAN belongs to the director. Please Note - This flag will only be applicable for Individual PAN', enum: ['Y', 'N'] },
      { name: 'isSoleProp',      in: 'body', required: false, type: 'string', description: 'If this is yes, it will whether given PAN belongs to the sole proprietor. Please Note - This flag will only be applicable for Individual PAN', enum: ['Y', 'N'] },
      { name: 'clientData',      in: 'body', required: false, type: 'object', description: 'Data of the user sharing consent' },
      { name: 'clientData.caseId', in: 'body', required: false, type: 'string', description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
    ],
    body: JSON.stringify({
      pan: 'D********F',
      aadhaarLastFour: '0908',
      dob: 'YYYY-MM-DD',
      name: 'Dhanashree Vinod Mirgal',
      address: '2/19 Kunti Devi Agarwal Nagar Caves Road Jogeshwari East Mumbai-400060',
      getContactDetails: 'Y',
      PANStatus: 'Y',
      isSalaried: 'Y',
      isDirector: 'Y',
      isSoleProp: 'Y',
      consent: 'Y',
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'requestId',  type: 'string',  required: true, description: 'Unique id of the API request.' },
      { field: 'result',     type: 'object',  required: true, description: 'Response object for the given inputs.' },
      { field: 'result.pan',        type: 'string',  required: false, description: 'PAN of the Individual/Entity' },
      { field: 'result.name',       type: 'string',  required: false, description: 'Full Name of the Individual/Entity as per Income Tax Records' },
      { field: 'result.firstName',  type: 'string',  required: false, description: 'First Name of the Individual' },
      { field: 'result.middleName', type: 'string',  required: false, description: 'Middle Name of the Individual' },
      { field: 'result.lastName',   type: 'string',  required: false, description: 'Last Name of the Individual' },
      { field: 'result.gender',     type: 'string',  required: false, description: 'Gender of the Individual (Not Applicable for Entity PAN)' },
      { field: 'result.aadhaarLinked', type: 'boolean', required: false, description: 'Whether an Aadhaar is linked to the PAN (Not Applicable for Entity PAN)' },
      { field: 'result.aadhaarMatch',  type: 'boolean', required: false, description: 'Whether given 4 digits of aadhaar match with last four digits as per Income Tax Records (Not Applicable for Entity PAN)' },
      { field: 'result.dob',        type: 'string',  required: false, description: 'Date of Birth/Incorporation as per Income Tax Records' },
      { field: 'result.address',    type: 'object',  required: false, description: 'Address Details of the Individual/Entity as per Income Tax Records' },
      ...addressFields('result.address'),
      { field: 'result.mobileNo',   type: 'string',  required: false, description: 'Mobile Number registered with Income Tax for Individual/Entity' },
      { field: 'result.emailId',    type: 'string',  required: false, description: 'Email ID registered with Income Tax' },
      { field: 'result.profileMatch', type: 'array', required: false, description: 'Data matching across shared input profile and Income Tax Records (in response)' },
      { field: 'result.profileMatch[].parameter',   type: 'string',  required: false, description: 'Given parameter [name, dob, address]' },
      { field: 'result.profileMatch[].matchScore',  type: 'integer', required: false, description: 'Match Score' },
      { field: 'result.profileMatch[].matchResult', type: 'boolean', required: false, description: 'Whether Match is Positive/Valid' },
      { field: 'result.authorizedSignatory', type: 'object', required: false, description: 'Profile Details of Authorized Signatory linked to the Entity PAN (Not Applicable for Individual PAN)' },
      { field: 'result.authorizedSignatory.pan',        type: 'string', required: false, description: 'PAN of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.name',       type: 'string', required: false, description: 'Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.firstName',  type: 'string', required: false, description: 'First Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.middleName', type: 'string', required: false, description: 'Middle Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.lastName',   type: 'string', required: false, description: 'Last Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.gender',     type: 'string', required: false, description: 'Gender of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.aadhaarLinked', type: 'string', required: false, description: "Whether an Aadhaar is linked to the Authorized Signatory's PAN" },
      { field: 'result.authorizedSignatory.dob',        type: 'string', required: false, description: 'Date of Birth of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.mobileNo',   type: 'string', required: false, description: 'Mobile No of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.emailId',    type: 'string', required: false, description: 'Email ID of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.address',    type: 'object', required: false, description: 'Address Details of the Authorized Signatory as per Income Tax Records' },
      ...addressFields('result.authorizedSignatory.address'),
      { field: 'result.status',    type: 'string',  required: false, description: 'Status of the PAN [Active or Inactive]' },
      { field: 'result.issueDate', type: 'string',  required: false, description: 'PAN Card Issue date' },
      { field: 'result.isSalaried', type: 'boolean', required: false, description: 'Whether given PAN belongs to Salaried individual [ True or False ]' },
      { field: 'result.isDirector', type: 'boolean', required: false, description: 'Whether given PAN belongs to a Director of organization [ True or False ]' },
      { field: 'result.isSoleProp', type: 'boolean', required: false, description: 'Whether given PAN belongs to a Sole Proprietor [ True or False ]' },
      { field: 'clientData',        type: 'object',  required: true,  description: 'Data of the user sharing consent' },
      { field: 'clientData.caseId', type: 'string',  required: true,  description: 'Unique case id/lead id of the user sharing consent' },
    ],
    body: JSON.stringify({
      requestId: 'd041f16d-902f-4ced-a365-427de20f2e78',
      result: {
        pan: 'D********F',
        name: 'DHANASHREE VINOD MIRGAL',
        firstName: 'DHANASHREE',
        middleName: 'VINOD',
        lastName: 'MIRGAL',
        gender: 'female',
        aadhaarLinked: true,
        aadhaarMatch: true,
        dob: 'YYYY-MM-DD',
        address: {
          buildingName: '2/19 RAM WADI KUNTIDEVI',
          locality: 'JOGESHWARI EAST',
          streetName: 'AGARWAL NGR CAVES RD',
          pinCode: '400060',
          city: 'MUMBAI',
          state: 'MAHARASHTRA',
          country: '',
        },
        mobileNo: null,
        emailId: null,
        profileMatch: [
          { parameter: 'address', matchScore: 0.99, matchResult: true },
          { parameter: 'name', matchScore: 1, matchResult: true },
          { parameter: 'dob', matchScore: 1, matchResult: true },
        ],
        authorizedSignatory: {
          pan: '', name: '', firstName: '', middleName: '', lastName: '',
          gender: '', aadhaarLinked: null, dob: '', mobileNo: '', emailId: '',
          address: { buildingName: '', locality: '', streetName: '', pinCode: '', city: '', state: '', country: '' },
        },
        status: 'Active',
        issueDate: '2016-06-28',
        isSalaried: true,
        isDirector: false,
        isSoleProp: false,
      },
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

// ── PAN Lite Details variant ──────────────────────────────────────────────────

const LITE: ApiVariant = {
  label: 'Basic profile (lite)',
  request: {
    params: [
      { name: 'consent', in: 'body', required: true, type: 'string', description: 'Consent is required to make the API request.', enum: ['Y', 'N'] },
      { name: 'pan',     in: 'body', required: true, type: 'string', label: 'PAN Number', uppercase: true, placeholder: 'ABCDE1234F', description: 'PAN of the Individual/Entity', example: 'minLength: 10 maxLength: 10 pattern: ^[A-Za-z]{5}\\d{4}[A-Za-z]{1}$' },
      { name: 'lite',    in: 'body', required: true, type: 'string', description: 'If this is yes, it will return limited details of given PAN', enum: ['Y', 'N'] },
      { name: 'clientData',        in: 'body', required: false, type: 'object', description: 'Data of the user sharing consent' },
      { name: 'clientData.caseId', in: 'body', required: false, type: 'string', description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
    ],
    body: JSON.stringify({
      pan: 'ABCDE6207P',
      lite: 'Y',
      consent: 'Y',
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'requestId',  type: 'string',  required: true, description: 'Unique id of the API request.' },
      { field: 'result',     type: 'object',  required: true, description: 'Response object for the given inputs.' },
      { field: 'result.pan',        type: 'string', required: false, description: 'PAN of the Individual/Entity' },
      { field: 'result.name',       type: 'string', required: false, description: 'Full Name of the Individual/Entity as per Income Tax Records' },
      { field: 'result.firstName',  type: 'string', required: false, description: 'First Name of the Individual' },
      { field: 'result.middleName', type: 'string', required: false, description: 'Middle Name of the Individual' },
      { field: 'result.lastName',   type: 'string', required: false, description: 'Last Name of the Individual' },
      { field: 'result.gender',     type: 'string', required: false, description: 'Gender of the Individual (Not Applicable for Entity PAN)' },
      { field: 'result.aadhaarLinked', type: 'string', required: false, description: 'Whether an Aadhaar is linked to the PAN (Not Applicable for Entity PAN)' },
      { field: 'result.aadhaarMatch',  type: 'string', required: false, description: 'Whether given 4 digits of aadhaar match with last four digits as per Income Tax Records (Not Applicable for Entity PAN)' },
      { field: 'result.dob',        type: 'string', required: false, description: 'Date of Birth/Incorporation as per Income Tax Records' },
      { field: 'result.address',    type: 'object', required: false, description: 'Address Details of the Individual/Entity as per Income Tax Records' },
      ...addressFields('result.address'),
      { field: 'result.profileMatch',        type: 'array',  required: false, description: 'Data matching across shared input profile and Income Tax Records (in response)' },
      { field: 'result.authorizedSignatory', type: 'object', required: false, description: 'Profile Details of Authorized Signatory linked to the Entity PAN (Not Applicable for Individual PAN)' },
      { field: 'clientData',        type: 'object', required: true, description: 'Data of the user sharing consent' },
      { field: 'clientData.caseId', type: 'string', required: true, description: 'Unique case id/lead id of the user sharing consent' },
    ],
    body: JSON.stringify({
      requestId: 'c1c690f0-9c68-47b0-9128-416351664afb',
      result: {
        pan: 'ABCDE6207P',
        name: 'KUMAR PATEL',
        firstName: 'KUMAR',
        middleName: '',
        lastName: 'PATEL',
        gender: 'MALE',
        aadhaarLinked: null,
        aadhaarMatch: null,
        dob: '1995-04-10',
        address: {
          buildingName: 'KUMAR PATEL NEAR GANGA MANGAL KARYALA',
          locality: '',
          streetName: 'VIDYA NAGAR',
          pinCode: '123456',
          city: 'PUNE',
          state: 'MAHARASHTRA',
          country: '',
        },
        profileMatch: [],
        authorizedSignatory: {},
      },
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

// ── Father Name variant ───────────────────────────────────────────────────────

const FATHER_NAME: ApiVariant = {
  label: 'Full profile with father name',
  request: {
    params: [
      { name: 'consent',          in: 'body', required: true,  type: 'string', description: 'Consent is required to make the API request.', enum: ['Y', 'N'] },
      { name: 'pan',              in: 'body', required: true,  type: 'string', label: 'PAN Number', uppercase: true, placeholder: 'ABCDE1234F', description: 'PAN of the Individual/Entity', example: 'minLength: 10 maxLength: 10 pattern: ^[A-Za-z]{5}\\d{4}[A-Za-z]{1}$' },
      { name: 'aadhaarLastFour',  in: 'body', required: false, type: 'string', description: 'Last 4 digits of the Aadhaar No (applicable only for individual PAN)', example: 'minLength: 4 maxLength: 4' },
      { name: 'dob',             in: 'body', required: false, type: 'string', label: 'Date of Birth', placeholder: 'YYYY-MM-DD', description: 'Date of Birth/Incorporation for the Individual/Entity', example: 'YYYY-MM-DD' },
      { name: 'name',            in: 'body', required: false, type: 'string', description: 'Name to be matched with the response for the Individual/Entity' },
      { name: 'address',         in: 'body', required: false, type: 'string', description: 'Address to be matched with the response for the Individual/Entity' },
      { name: 'getContactDetails', in: 'body', required: true,  type: 'string', description: 'It will return email and contact number' },
      { name: 'fatherName',      in: 'body', required: false, type: 'string', description: '-' },
      { name: 'PANStatus',       in: 'body', required: true,  type: 'string', description: 'It will return PAN status and PAN issue date' },
      { name: 'isSalaried',      in: 'body', required: true,  type: 'string', description: 'It will check whether given PAN belongs to a salaried individual. Please Note - This flag will only be applicable for Individual PAN' },
      { name: 'isDirector',      in: 'body', required: true,  type: 'string', description: 'It will check whether given PAN belongs to the director. Please Note - This flag will only be applicable for Individual PAN' },
      { name: 'isSoleProp',      in: 'body', required: true,  type: 'string', description: 'It will check whether given PAN belongs to the sole proprietor. Please Note - This flag will only be applicable for Individual PAN' },
      { name: 'clientData',      in: 'body', required: false, type: 'object', description: 'Data of the user sharing consent' },
      { name: 'clientData.caseId', in: 'body', required: false, type: 'string', description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
    ],
    body: JSON.stringify({
      pan: 'D********F',
      aadhaarLastFour: '0908',
      dob: 'YYYY-MM-DD',
      name: 'Dhanashree Vinod Mirgal',
      address: '2/19 Kunti Devi Agarwal Nagar Caves Road Jogeshwari East Mumbai-400060',
      getContactDetails: 'Y',
      fatherName: 'Y',
      PANStatus: 'Y',
      isSalaried: 'Y',
      isDirector: 'Y',
      isSoleProp: 'Y',
      consent: 'Y',
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'requestId',  type: 'string',  required: true, description: 'Unique id of the API request.' },
      { field: 'result',     type: 'object',  required: true, description: 'Response object for the given inputs.' },
      { field: 'result.pan',        type: 'string',  required: false, description: 'PAN of the Individual/Entity' },
      { field: 'result.name',       type: 'string',  required: false, description: 'Full Name of the Individual/Entity as per Income Tax Records' },
      { field: 'result.firstName',  type: 'string',  required: false, description: 'First Name of the Individual' },
      { field: 'result.middleName', type: 'string',  required: false, description: 'Middle Name of the Individual' },
      { field: 'result.lastName',   type: 'string',  required: false, description: 'Last Name of the Individual' },
      { field: 'result.gender',     type: 'string',  required: false, description: 'Gender of the Individual (Not Applicable for Entity PAN)' },
      { field: 'result.aadhaarLinked', type: 'boolean', required: false, description: 'Whether an Aadhaar is linked to the PAN (Not Applicable for Entity PAN)' },
      { field: 'result.aadhaarMatch',  type: 'boolean', required: false, description: 'Whether given 4 digits of aadhaar match with last four digits as per Income Tax Records (Not Applicable for Entity PAN)' },
      { field: 'result.dob',        type: 'string',  required: false, description: 'Date of Birth/Incorporation as per Income Tax Records' },
      { field: 'result.address',    type: 'object',  required: false, description: 'Address Details of the Individual/Entity as per Income Tax Records' },
      ...addressFields('result.address'),
      { field: 'result.mobileNo',   type: 'string',  required: false, description: 'Mobile Number registered with Income Tax for Individual/Entity' },
      { field: 'result.emailId',    type: 'string',  required: false, description: 'Email ID registered with Income Tax' },
      { field: 'result.profileMatch', type: 'array', required: false, description: 'Data matching across shared input profile and Income Tax Records (in response)' },
      { field: 'result.profileMatch[].parameter',   type: 'string',  required: false, description: 'Given parameter [name, dob, address]' },
      { field: 'result.profileMatch[].matchScore',  type: 'integer', required: false, description: 'Match Score' },
      { field: 'result.profileMatch[].matchResult', type: 'boolean', required: false, description: 'Whether Match is Positive/Valid' },
      { field: 'result.authorizedSignatory', type: 'object', required: false, description: 'Profile Details of Authorized Signatory linked to the Entity PAN (Not Applicable for Individual PAN)' },
      { field: 'result.authorizedSignatory.pan',        type: 'string', required: false, description: 'PAN of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.name',       type: 'string', required: false, description: 'Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.firstName',  type: 'string', required: false, description: 'First Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.middleName', type: 'string', required: false, description: 'Middle Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.lastName',   type: 'string', required: false, description: 'Last Name of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.gender',     type: 'string', required: false, description: 'Gender of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.aadhaarLinked', type: 'string', required: false, description: "Whether an Aadhaar is linked to the Authorized Signatory's PAN" },
      { field: 'result.authorizedSignatory.dob',        type: 'string', required: false, description: 'Date of Birth of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.mobileNo',   type: 'string', required: false, description: 'Mobile No of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.emailId',    type: 'string', required: false, description: 'Email ID of the Authorized Signatory' },
      { field: 'result.authorizedSignatory.address',    type: 'object', required: false, description: 'Address Details of the Authorized Signatory as per Income Tax Records' },
      ...addressFields('result.authorizedSignatory.address'),
      { field: 'result.status',     type: 'string',  required: false, description: 'Status of the PAN [Active or Inactive]' },
      { field: 'result.fatherName', type: 'string',  required: false, description: '-' },
      { field: 'result.issueDate',  type: 'string',  required: false, description: 'PAN Card Issue date' },
      { field: 'result.isSalaried', type: 'boolean', required: false, description: 'Whether given PAN belongs to Salaried individual [ True or False ]' },
      { field: 'result.isDirector', type: 'boolean', required: false, description: 'Whether given PAN belongs to a Director of organization [ True or False ]' },
      { field: 'result.isSoleProp', type: 'boolean', required: false, description: 'Whether given PAN belongs to a Sole Proprietor [ True or False ]' },
      { field: 'clientData',        type: 'object',  required: true,  description: 'Data of the user sharing consent' },
      { field: 'clientData.caseId', type: 'string',  required: true,  description: 'Unique case id/lead id of the user sharing consent' },
    ],
    body: JSON.stringify({
      requestId: 'd041f16d-902f-4ced-a365-427de20f2e78',
      result: {
        pan: 'D********F',
        name: 'DHANASHREE VINOD MIRGAL',
        firstName: 'DHANASHREE',
        middleName: 'VINOD',
        lastName: 'MIRGAL',
        gender: 'female',
        aadhaarLinked: true,
        aadhaarMatch: true,
        dob: 'YYYY-MM-DD',
        address: {
          buildingName: '2/19 RAM WADI KUNTIDEVI',
          locality: 'JOGESHWARI EAST',
          streetName: 'AGARWAL NGR CAVES RD',
          pinCode: '400060',
          city: 'MUMBAI',
          state: 'MAHARASHTRA',
          country: '',
        },
        mobileNo: null,
        emailId: null,
        profileMatch: [
          { parameter: 'address', matchScore: 0.99, matchResult: true },
          { parameter: 'name', matchScore: 1, matchResult: true },
          { parameter: 'dob', matchScore: 1, matchResult: true },
        ],
        authorizedSignatory: {
          pan: '', name: '', firstName: '', middleName: '', lastName: '',
          gender: '', aadhaarLinked: null, dob: '', mobileNo: '', emailId: '',
          address: { buildingName: '', locality: '', streetName: '', pinCode: '', city: '', state: '', country: '' },
        },
        status: 'Active',
        fatherName: 'VINOD Mirgal',
        issueDate: '2016-06-28',
        isSalaried: true,
        isDirector: false,
        isSoleProp: false,
      },
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

export const PAN_PROFILE_VARIANTS: ApiVariant[] = [DEFAULT, LITE, FATHER_NAME]
