import type { ApiVariant } from './api-definitions'

const HEADERS_WITH_KEY = `Content-Type : "application/json"\nx-karza-key: "<<YOUR KEY HERE>>"`
const HEADERS_JSON_ONLY = `Content-Type : "application/json"`

const REQUEST_PARAMS = [
  { name: 'consent', in: 'body' as const, required: true, type: 'string' as const, enum: ['Y', 'N'], description: 'Consent is required to make the API request.' },
  { name: 'email', in: 'body' as const, required: false, type: 'string' as const, description: 'Given email id in the format example@example.com' },
  { name: 'ipAddress', in: 'body' as const, required: false, type: 'string' as const, description: 'IP address of the owner (Supported IP formats - IPv4, IPv6, IPv6 Compressed)' },
  { name: 'firstName', in: 'body' as const, required: false, type: 'string' as const, description: 'First name of the owner of given email ID' },
  { name: 'lastName', in: 'body' as const, required: false, type: 'string' as const, description: 'Last name of the owner of given email ID' },
  { name: 'clientData', in: 'body' as const, required: false, type: 'object' as const, description: 'Data of the user sharing consent' },
  { name: 'clientData.caseId', in: 'body' as const, required: false, type: 'string' as const, description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
]

function responseFields(prefix: string) {
  return [
    { field: `${prefix}result`, type: 'array', required: false, description: 'Response object for the given inputs' },
    { field: `${prefix}result[].emailOwnerDetails`, type: 'object', required: false, description: 'Details of email owner' },
    { field: `${prefix}result[].emailOwnerDetails.email`, type: 'string', required: false, description: 'Email Id as entered in input' },
    { field: `${prefix}result[].emailOwnerDetails.name`, type: 'string', required: false, description: 'Name of the person associated with email ID' },
    { field: `${prefix}result[].emailOwnerDetails.company`, type: 'string', required: false, description: 'Company name associated with email ID' },
    { field: `${prefix}result[].emailOwnerDetails.title`, type: 'string', required: false, description: 'Title of the person associated with the email ID' },
    { field: `${prefix}result[].emailOwnerDetails.nameMatch`, type: 'string', required: false, description: 'Whether the name provided in input matches the email owner name. Y: FULL MATCH, P: PARTIAL MATCH, N: NO MATCH, U: OWNER UNKNOWN, NULL: if no value passed' },
    { field: `${prefix}result[].emailOwnerDetails.location`, type: 'string', required: false, description: 'Location of the person associated with the email ID' },
    { field: `${prefix}result[].domainDetails`, type: 'object', required: false, description: 'Details of domain' },
    { field: `${prefix}result[].domainDetails.domainName`, type: 'string', required: false, description: 'Name of domain' },
    { field: `${prefix}result[].domainDetails.domainCompany`, type: 'string', required: false, description: 'Company of domain' },
    { field: `${prefix}result[].domainDetails.country`, type: 'string', required: false, description: 'Domain country code' },
    { field: `${prefix}result[].domainDetails.domainCountryName`, type: 'string', required: false, description: 'Country of the domain to which the email belongs' },
    { field: `${prefix}result[].domainDetails.domainCategory`, type: 'string', required: false, description: 'Category type of the company in which the email belongs' },
    { field: `${prefix}result[].domainDetails.domainCorporate`, type: 'string', required: false, description: 'Indicates if the domain is corporate. Expected Values - Yes/No/Null' },
    { field: `${prefix}result[].socialMediaDetails`, type: 'object', required: false, description: 'Email Social Media Related Fields' },
    { field: `${prefix}result[].socialMediaDetails.smlinks`, type: 'array', required: false, description: 'Details of social media sites that match the email' },
    { field: `${prefix}result[].socialMediaDetails.smlinks[].source`, type: 'string', required: false, description: 'Source of social media site' },
    { field: `${prefix}result[].socialMediaDetails.smlinks[].link`, type: 'string', required: false, description: 'URL of the social media site that matches the email' },
    { field: `${prefix}result[].socialMediaDetails.smfriends`, type: 'string', required: false, description: 'Number of social media friends/connections found' },
    { field: `${prefix}result[].socialMediaDetails.image`, type: 'string', required: false, description: 'Base64 profile image associated with the email, if found' },
    { field: `${prefix}result[].emailAndDomainValidationDetails`, type: 'object', required: false, description: 'Email and domain validation details' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.emailExists`, type: 'string', required: false, description: 'Whether the email exists' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.domainAge`, type: 'string', required: false, description: 'Domain registration/creation timestamp' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.domainCreationDays`, type: 'string', required: false, description: 'Number of days since domain creation' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.emailAge`, type: 'string', required: false, description: 'Email account age' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.emailCreationDays`, type: 'string', required: false, description: 'Number of days since email creation' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.firstVerificationDate`, type: 'string', required: false, description: 'Date the email was first verified in the vendor database' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.firstSeenDays`, type: 'string', required: false, description: 'Number of days since the email was first seen' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.lastVerificationDate`, type: 'string', required: false, description: 'Date the email was last verified' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.totalHits`, type: 'string', required: false, description: 'Total number of hits/lookups for this email' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.uniqueHits`, type: 'string', required: false, description: 'Number of unique hits/lookups for this email' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.statusId`, type: 'string', required: false, description: 'Status ID — see "Expected values 1.1 - StatusID and Status"' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.status`, type: 'string', required: false, description: 'Status description (e.g. ValidDomain, Certified, Verified)' },
    { field: `${prefix}result[].emailAndDomainValidationDetails.domainExists`, type: 'string', required: false, description: 'Whether the domain exists' },
    { field: `${prefix}result[].emailAndDomainRiskDetails`, type: 'object', required: false, description: 'Email and domain fraud risk assessment' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.score`, type: 'string', required: false, description: 'Fraud risk score' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.fraudRisk`, type: 'string', required: false, description: 'Fraud risk band label' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.reasonId`, type: 'string', required: false, description: 'Reason ID for the risk assessment' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.reason`, type: 'string', required: false, description: 'Reason description for the risk assessment' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.adviceId`, type: 'string', required: false, description: 'Advice ID — see "Expected values 1.2 - AdviceID and Advice"' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.advice`, type: 'string', required: false, description: 'Advice description (e.g. Lower Fraud Risk)' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.riskBandId`, type: 'string', required: false, description: 'Risk band ID — see "Expected values 1.3 - Risk Band ID and Risk Band"' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.riskBand`, type: 'string', required: false, description: 'Risk band description' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.sourceIndustry`, type: 'string', required: false, description: 'Reporting source industry — see "Expected values 1.4 - Source Industry"' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.fraudType`, type: 'string', required: false, description: 'Fraud type reported — see "Expected values 1.5 - Fraud Type"' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.lastFlaggedOn`, type: 'string', required: false, description: 'Date the email/domain was last flagged for fraud' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.domainRiskLevelId`, type: 'string', required: false, description: 'Domain risk level ID — see "Expected values 1.6 - Domain Risk Level ID and Domain Risk Level"' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.domainRiskLevel`, type: 'string', required: false, description: 'Domain risk level description' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.domainRiskLevelInfoId`, type: 'string', required: false, description: 'Domain risk level info ID (nullable)' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.domainRiskLevelInfo`, type: 'string', required: false, description: 'Domain risk level info detail (nullable)' },
    { field: `${prefix}result[].emailAndDomainRiskDetails.domainRiskCountry`, type: 'string', required: false, description: 'Whether the domain risk is country-related' },
    { field: `${prefix}result[].ipDetails`, type: 'object', required: false, description: 'IP address reputation details' },
    { field: `${prefix}result[].ipDetails.ipAddress`, type: 'string', required: false, description: 'IP address checked' },
    { field: `${prefix}result[].ipDetails.ipReputation`, type: 'string', required: false, description: 'Reputation of the IP address' },
    { field: `${prefix}result[].ipDetails.ipAnonymousDetected`, type: 'string', required: false, description: 'Whether an anonymizing proxy/VPN was detected' },
    { field: `${prefix}result[].ipDetails.ipProxyType`, type: 'string', required: false, description: 'Type of proxy detected, if any' },
    { field: `${prefix}result[].ipDetails.ipProxyDescription`, type: 'string', required: false, description: 'Description of the detected proxy' },
    { field: `${prefix}result[].ipDetails.ipIsp`, type: 'string', required: false, description: 'ISP of the IP address' },
    { field: `${prefix}result[].ipDetails.ipOrg`, type: 'string', required: false, description: 'Organization associated with the IP address' },
    { field: `${prefix}result[].ipDetails.ipUserType`, type: 'string', required: false, description: 'Type of user connection (e.g. wired)' },
    { field: `${prefix}result[].ipDetails.ipNetSpeedCell`, type: 'string', required: false, description: 'Network speed classification' },
    { field: `${prefix}result[].ipDetails.ipCorporateProxy`, type: 'string', required: false, description: 'Whether the IP is a corporate proxy' },
    { field: `${prefix}result[].ipLocationDetails`, type: 'object', required: false, description: 'IP-derived geolocation details' },
    { field: `${prefix}result[].ipLocationDetails.ipLatitude`, type: 'string', required: false, description: 'Latitude of the IP location' },
    { field: `${prefix}result[].ipLocationDetails.ipLongitude`, type: 'string', required: false, description: 'Longitude of the IP location' },
    { field: `${prefix}result[].ipLocationDetails.ipRegion`, type: 'string', required: false, description: 'Region of the IP location' },
    { field: `${prefix}result[].ipLocationDetails.ipCity`, type: 'string', required: false, description: 'City of the IP location' },
    { field: `${prefix}result[].ipLocationDetails.ipRegionConf`, type: 'string', required: false, description: 'Confidence score for region detection' },
    { field: `${prefix}result[].ipLocationDetails.ipCityConf`, type: 'string', required: false, description: 'Confidence score for city detection' },
    { field: `${prefix}result[].ipLocationDetails.ipPostalCode`, type: 'string', required: false, description: 'Postal code of the IP location' },
    { field: `${prefix}result[].ipLocationDetails.ipPostalConf`, type: 'string', required: false, description: 'Confidence score for postal code detection' },
    { field: `${prefix}result[].ipAndDeviceDetails`, type: 'object', required: false, description: 'IP and device risk details' },
    { field: `${prefix}result[].ipAndDeviceDetails.ipRiskLevelId`, type: 'string', required: false, description: 'IP risk level ID' },
    { field: `${prefix}result[].ipAndDeviceDetails.ipRiskLevel`, type: 'string', required: false, description: 'IP risk level description' },
    { field: `${prefix}result[].ipAndDeviceDetails.ipRiskReasonId`, type: 'string', required: false, description: 'IP risk reason ID' },
    { field: `${prefix}result[].ipAndDeviceDetails.ipRiskReason`, type: 'string', required: false, description: 'IP risk reason description' },
    { field: `${prefix}result[].ipAndDeviceDetails.ipRiskCountry`, type: 'string', required: false, description: 'Whether the IP risk is country-related' },
    { field: `${prefix}result[].ipAndDeviceDetails.deviceRiskLevel`, type: 'string', required: false, description: 'Device risk level (nullable)' },
  ]
}

const EXAMPLE_RESULT_ITEM = {
  emailOwnerDetails: {
    email: 'kailas@dhyeyapurti.org',
    name: 'Kailas Adhav',
    company: 'Chairman :- Dhyeyapurti Seva....& Pro. Turiya Infotech, Nashik',
    title: 'Service Provider',
    nameMatch: 'P',
    location: 'Nashik, India',
  },
  domainDetails: {
    domainName: 'dhyeyapurti.org',
    domainCompany: '',
    country: 'IN',
    domainCountryName: 'India',
    domainCategory: '',
    domainCorporate: '',
  },
  socialMediaDetails: {
    smlinks: [
      { source: 'Gravatar', link: 'https://gravatar.com/dhyeyapurti' },
      { source: 'GoogleSearch', link: 'https://plus.google.com/112013897399021985329' },
      { source: 'Klout', link: 'http://klout.com/kailasadhav' },
      { source: 'Twitter', link: 'https://twitter.com/kailasadhav' },
      { source: 'Foursquare', link: 'https://foursquare.com/user/6536967' },
    ],
    smfriends: '539',
    image: "b'/9j/4AAQSkZJRgABAQAAAQABAAD...",
  },
  emailAndDomainValidationDetails: {
    emailExists: 'Not Sure',
    domainAge: '2009-02-28 05:30:00',
    domainCreationDays: '4678',
    emailAge: '',
    emailCreationDays: '',
    firstVerificationDate: '2012-05-22 05:30:00',
    firstSeenDays: '3499',
    lastVerificationDate: '2021-12-20 14:55:09',
    totalHits: '47',
    uniqueHits: '1',
    statusId: '4',
    status: 'ValidDomain',
    domainExists: 'Yes',
  },
  emailAndDomainRiskDetails: {
    score: '73',
    fraudRisk: '073 Very Low',
    reasonId: '14',
    reason: 'Email Created at least 9.6 Years Ago',
    adviceId: '3',
    advice: 'Lower Fraud Risk',
    riskBandId: '1',
    riskBand: 'Fraud Score 1 to 100',
    sourceIndustry: '',
    fraudType: '',
    lastFlaggedOn: '',
    domainRiskLevelId: '3',
    domainRiskLevel: 'Moderate',
    domainRiskLevelInfoId: null,
    domainRiskLevelInfo: null,
    domainRiskCountry: 'No',
  },
  ipDetails: {
    ipAddress: '141.161.19.1',
    ipReputation: 'Good',
    ipAnonymousDetected: 'No',
    ipProxyType: 'edu',
    ipProxyDescription: '',
    ipIsp: 'georgetown university',
    ipOrg: 'georgetown university',
    ipUserType: 'wired',
    ipNetSpeedCell: 'broadband',
    ipCorporateProxy: 'Yes',
  },
  ipLocationDetails: {
    ipLatitude: '38.910000',
    ipLongitude: '-77.080002',
    ipRegion: 'district of columbia',
    ipCity: 'washington',
    ipRegionConf: '75',
    ipCityConf: '60',
    ipPostalCode: '20057',
    ipPostalConf: '35',
  },
  ipAndDeviceDetails: {
    ipRiskLevelId: '3',
    ipRiskLevel: 'Moderate',
    ipRiskReasonId: '311',
    ipRiskReason: 'Moderate By Proxy Reputation And Country Code',
    ipRiskCountry: '',
    deviceRiskLevel: null,
  },
}

const DEFAULT: ApiVariant = {
  label: 'Email fraud check',
  request: {
    params: REQUEST_PARAMS,
    body: JSON.stringify({
      email: 'kailas@dhyeyapurti.org',
      consent: 'Y',
      ipAddress: '141.161.19.1',
      firstName: 'Kailas',
      lastName: 'dhyey',
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'requestId', type: 'string', required: true, description: 'Unique id of the API request.' },
      ...responseFields(''),
      { field: 'clientData', type: 'object', required: true, description: 'Data of the user sharing consent' },
      { field: 'clientData.caseId', type: 'string', required: true, description: 'Unique case id/lead id of the user sharing consent' },
    ],
    body: JSON.stringify({
      requestId: '0d44f3e8-d1ec-44bb-b48b-ce065bd2eb15',
      result: [EXAMPLE_RESULT_ITEM],
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

export const EMAIL_FRAUD_VARIANTS: ApiVariant[] = [DEFAULT]
export { responseFields as emailFraudResponseFields }
