import type { ApiVariant } from './api-definitions'

const HEADERS_WITH_KEY = `Content-Type : "application/json"\nx-karza-key: "<<YOUR KEY HERE>>"`
const HEADERS_JSON_ONLY = `Content-Type : "application/json"`

const REQUEST_PARAMS = [
  { name: 'consent', in: 'body' as const, required: true, type: 'string' as const, enum: ['Y', 'N'], description: 'Consent is required to make the API request.' },
  { name: 'uans', in: 'body' as const, required: false, type: 'array' as const, description: 'UAN(s) allotted to the individual by EPFO', example: 'pattern: ^[0-9]{12}$ per item' },
  { name: 'entityId', in: 'body' as const, required: false, type: 'string' as const, description: 'Entity ID/CIN of the Company' },
  { name: 'employerName', in: 'body' as const, required: false, type: 'string' as const, description: 'Employer Name', example: 'minLength: 3 maxLength: 255' },
  { name: 'employeeName', in: 'body' as const, required: false, type: 'string' as const, description: 'Employee Name', example: 'minLength: 3 maxLength: 50' },
  { name: 'mobile', in: 'body' as const, required: false, type: 'string' as const, description: 'Mobile Number of the Individual', example: 'pattern: ^[6-9]\\d{9}$' },
  { name: 'emailId', in: 'body' as const, required: false, type: 'string' as const, description: 'Work Email of the Individual' },
  { name: 'runPanFlow', in: 'body' as const, required: true, type: 'boolean' as const, description: 'Trigger PAN Flow', example: '[true, false]' },
  { name: 'pan', in: 'body' as const, required: true, type: 'string' as const, uppercase: true, placeholder: 'DFKAB1295K', description: 'PAN number of the individual', example: 'minLength: 10 maxLength: 10' },
  { name: 'showFailures', in: 'body' as const, required: false, type: 'boolean' as const, description: 'Shows details regarding the failures', example: '[true, false]' },
  { name: 'isLatestEmployer', in: 'body' as const, required: false, type: 'boolean' as const, description: 'To trigger the latest employer flow', example: '[true, false]' },
  { name: 'pdf', in: 'body' as const, required: false, type: 'boolean' as const, description: 'If this is true then get the pdf link in the response', example: '[true, false]' },
  { name: 'clientData', in: 'body' as const, required: false, type: 'object' as const, description: 'Data of the user sharing consent' },
  { name: 'clientData.caseId', in: 'body' as const, required: false, type: 'string' as const, description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
]

function responseFields(prefix: string) {
  return [
    { field: `${prefix}result`, type: 'object', required: true, description: 'Response object for the given inputs.' },
    { field: `${prefix}result.email`, type: 'object', required: false, description: 'Details for Email Verification' },
    { field: `${prefix}result.email.additionalInfo`, type: 'object', required: false, description: 'Additional Information for the Given Email ID' },
    { field: `${prefix}result.email.additionalInfo.companyInfo`, type: 'object', required: false, description: 'Company Information' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgDomainMatch`, type: 'array', required: false, description: 'Array of Organization Domain Match — domain used by the given Organization for any statutory Business Registration [MCA, EPF, GST, IEC]' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgDomainMatch[].domain`, type: 'string', required: false, description: 'Domain used by the given Organization' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgDomainMatch[].match`, type: 'boolean', required: false, description: 'Whether the given domain matches with officially used domain of the given organization' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgDomainMatch[].orgName`, type: 'string', required: false, description: 'Given Organization Name' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgDomainMatch[].source`, type: 'string', required: false, description: 'Source from which the domain was identified' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgEmailMatch`, type: 'array', required: false, description: 'Array of Organization Email Match' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgEmailMatch[].companyEmail`, type: 'string', required: false, description: 'Email ID used by the given Organization for any statutory Business Registration' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgEmailMatch[].match`, type: 'boolean', required: false, description: 'Whether the given email matches with officially used email of the given organization' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgEmailMatch[].orgName`, type: 'string', required: false, description: 'Organization Name' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.orgEmailMatch[].source`, type: 'string', required: false, description: 'Source from which the email was identified' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.usrDirectorMatch`, type: 'array', required: false, description: 'Array of User Director Match' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.usrDirectorMatch[].match`, type: 'boolean', required: false, description: 'Whether the user matches a director/signatory of the organization' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.usrDirectorMatch[].name`, type: 'string', required: false, description: 'Matched director/signatory name' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.usrDirectorMatch[].orgName`, type: 'string', required: false, description: 'Organization Name' },
    { field: `${prefix}result.email.additionalInfo.companyInfo.usrDirectorMatch[].score`, type: 'float', required: false, description: 'Match score' },
    { field: `${prefix}result.email.additionalInfo.individualMatch`, type: 'array', required: false, description: 'Array of individual name match against the given email' },
    { field: `${prefix}result.email.additionalInfo.individualMatch[].match`, type: 'boolean', required: false, description: 'Whether the individual name matches' },
    { field: `${prefix}result.email.additionalInfo.individualMatch[].name`, type: 'string', required: false, description: 'Matched individual name' },
    { field: `${prefix}result.email.additionalInfo.individualMatch[].score`, type: 'float', required: false, description: 'Match score' },
    { field: `${prefix}result.email.additionalInfo.spamRecord`, type: 'object', required: false, description: 'Spam record for the given email' },
    { field: `${prefix}result.email.additionalInfo.spamRecord.spamEmail`, type: 'boolean', required: false, description: 'Whether flagged as a spam email' },
    { field: `${prefix}result.email.additionalInfo.spamRecord.reportCount`, type: 'integer', required: false, description: 'Number of spam reports' },
    { field: `${prefix}result.email.additionalInfo.spamRecord.ipBlacklist`, type: 'boolean', required: false, description: 'Whether the associated IP is blacklisted' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo`, type: 'object', required: false, description: 'WHOIS registration information for the email domain' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.ageYear`, type: 'float', required: false, description: 'Age of the domain in years' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.creationDate`, type: 'string', required: false, description: 'Domain creation date' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.expirationDate`, type: 'string', required: false, description: 'Domain expiration date' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.updateDate`, type: 'string', required: false, description: 'Domain last update date' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.expired`, type: 'boolean', required: false, description: 'Whether the domain registration has expired' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.whoisOrgName`, type: 'array', required: false, description: 'Array of organization name matches from WHOIS record' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.whoisOrgName[].match`, type: 'boolean', required: false, description: 'Whether the WHOIS org name matches' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.whoisOrgName[].orgName`, type: 'string', required: false, description: 'Matched organization name' },
    { field: `${prefix}result.email.additionalInfo.whoisInfo.whoisOrgName[].score`, type: 'float', required: false, description: 'Match score' },
    { field: `${prefix}result.email.data`, type: 'object', required: false, description: 'Raw email validation data' },
    { field: `${prefix}result.email.data.acceptAll`, type: 'boolean', required: false, description: 'Whether the mail server accepts all addresses (catch-all)' },
    { field: `${prefix}result.email.data.disposable`, type: 'boolean', required: false, description: 'Whether the email is a disposable/temporary address' },
    { field: `${prefix}result.email.data.email`, type: 'string', required: false, description: 'The email address checked' },
    { field: `${prefix}result.email.data.genericEmail`, type: 'boolean', required: false, description: 'Whether the email is a generic (non-personal) address' },
    { field: `${prefix}result.email.data.mxRecords`, type: 'boolean', required: false, description: 'Whether valid MX records exist for the domain' },
    { field: `${prefix}result.email.data.regexp`, type: 'boolean', required: false, description: 'Whether the email passed regex format validation' },
    { field: `${prefix}result.email.data.result`, type: 'boolean', required: false, description: 'Overall email data validity result' },
    { field: `${prefix}result.email.data.smtpCheck`, type: 'boolean', required: false, description: 'Whether SMTP check passed' },
    { field: `${prefix}result.email.data.webmail`, type: 'boolean', required: false, description: 'Whether the email belongs to a webmail provider' },
    { field: `${prefix}result.email.result`, type: 'boolean', required: false, description: 'Overall email verification result' },
    { field: `${prefix}result.nameLookup`, type: 'object', required: false, description: 'EPFO name lookup and employment history via UAN/PAN' },
    { field: `${prefix}result.nameLookup.organizationName`, type: 'string', required: false, description: 'Organization Name as submitted' },
    { field: `${prefix}result.nameLookup.epfHistory`, type: 'array', required: false, description: 'EPF contribution history by wage month' },
    { field: `${prefix}result.nameLookup.epfHistory[].totalAmount`, type: 'number', required: false, description: 'Total EPF contribution amount for the month' },
    { field: `${prefix}result.nameLookup.epfHistory[].totalMembers`, type: 'integer', required: false, description: 'Total number of members contributing that month' },
    { field: `${prefix}result.nameLookup.epfHistory[].formatted_wage_month`, type: 'string', required: false, description: 'Wage month in YYMM format' },
    { field: `${prefix}result.nameLookup.epfHistory[].wageMonth`, type: 'string', required: false, description: 'Wage month in MON-YY format' },
    { field: `${prefix}result.nameLookup.estInfo`, type: 'array', required: false, description: 'Establishment info matched for the individual' },
    { field: `${prefix}result.nameLookup.estInfo[].address`, type: 'string', required: false, description: 'Establishment address' },
    { field: `${prefix}result.nameLookup.estInfo[].contactNo`, type: 'string', required: false, description: 'Establishment contact number' },
    { field: `${prefix}result.nameLookup.estInfo[].emailId`, type: 'string', required: false, description: 'Establishment email ID' },
    { field: `${prefix}result.nameLookup.estInfo[].estId`, type: 'string', required: false, description: 'Establishment ID (EPFO)' },
    { field: `${prefix}result.nameLookup.matches`, type: 'array', required: false, description: 'Name match results across EPF records' },
    { field: `${prefix}result.nameLookup.matches[].name`, type: 'string', required: false, description: 'Matched name in EPF records' },
    { field: `${prefix}result.nameLookup.matches[].confidence`, type: 'float', required: false, description: 'Confidence score of the name match' },
    { field: `${prefix}result.nameLookup.matches[].estId`, type: 'string', required: false, description: 'Establishment ID' },
    { field: `${prefix}result.nameLookup.matches[].epfHistory`, type: 'object', required: false, description: 'Map of wage month to whether a contribution was found' },
    { field: `${prefix}result.nameLookup.isNameExact`, type: 'boolean', required: false, description: 'Whether the name match is exact' },
    { field: `${prefix}result.nameLookup.isEmployed`, type: 'boolean', required: false, description: 'Whether the individual is currently employed per EPFO records' },
    { field: `${prefix}result.nameLookup.isRecent`, type: 'boolean', required: false, description: 'Whether the employment record is recent' },
    { field: `${prefix}result.nameLookup.isNameUnique`, type: 'boolean', required: false, description: 'Whether the matched name is unique among records' },
    { field: `${prefix}result.nameLookup.employeeName`, type: 'string', required: false, description: 'Employee name used for the lookup' },
    { field: `${prefix}result.uan`, type: 'array', required: false, description: 'UAN(s) found for the individual, with employer history per UAN' },
    { field: `${prefix}result.uan[].uan`, type: 'string', required: false, description: 'UAN number' },
    { field: `${prefix}result.uan[].uanSource`, type: 'string', required: false, description: 'Source that surfaced the UAN (e.g. "pan")' },
    { field: `${prefix}result.uan[].employer`, type: 'array', required: false, description: 'Employer history under this UAN' },
    { field: `${prefix}result.uan[].employer[].name`, type: 'string', required: false, description: 'Employer name' },
    { field: `${prefix}result.uan[].employer[].memberId`, type: 'string', required: false, description: 'EPFO member ID for this employment' },
    { field: `${prefix}result.uan[].employer[].settled`, type: 'boolean', required: false, description: 'Whether the EPF account was settled (nullable)' },
    { field: `${prefix}result.uan[].employer[].dateOfExit`, type: 'string', required: false, description: 'Date of exit from this employer (nullable)' },
    { field: `${prefix}result.uan[].employer[].dateOfJoining`, type: 'string', required: false, description: 'Date of joining this employer' },
    { field: `${prefix}result.uan[].employer[].lastMonthYear`, type: 'string', required: false, description: 'Last month/year of contribution' },
    { field: `${prefix}result.uan[].employer[].startMonthYear`, type: 'string', required: false, description: 'Starting month/year of contribution' },
    { field: `${prefix}result.uan[].employer[].employmentPeriod`, type: 'integer', required: false, description: 'Employment period in months (nullable)' },
    { field: `${prefix}result.uan[].employer[].isNameUnique`, type: 'boolean', required: false, description: 'Whether the matched name is unique for this employer' },
    { field: `${prefix}result.uan[].employer[].matchName`, type: 'string', required: false, description: 'Matched name for this employer record (nullable)' },
    { field: `${prefix}result.uan[].employer[].lastMonth`, type: 'string', required: false, description: 'Last wage month contributed (YYMM)' },
    { field: `${prefix}result.uan[].employer[].isRecent`, type: 'boolean', required: false, description: 'Whether this employment is recent' },
    { field: `${prefix}result.uan[].employer[].isNameExact`, type: 'boolean', required: false, description: 'Whether the name match is exact for this employer' },
    { field: `${prefix}result.uan[].employer[].isEmployed`, type: 'boolean', required: false, description: 'Whether currently employed at this employer' },
    { field: `${prefix}result.uan[].employer[].nameConfidence`, type: 'float', required: false, description: 'Confidence score of the name match (nullable)' },
    { field: `${prefix}result.uan[].employer[].emplrScore`, type: 'float', required: false, description: 'Employer match score' },
    { field: `${prefix}result.uan[].employer[].uanNameMatch`, type: 'boolean', required: false, description: 'Whether the UAN name matches the input' },
    { field: `${prefix}result.uan[].failures`, type: 'array', required: false, description: 'Failures encountered for this UAN' },
    { field: `${prefix}result.personalInfo`, type: 'object', required: false, description: 'Personal information from PAN/EPFO records' },
    { field: `${prefix}result.personalInfo.name`, type: 'string', required: false, description: 'Full name' },
    { field: `${prefix}result.personalInfo.dateOfBirth`, type: 'string', required: false, description: 'Date of birth' },
    { field: `${prefix}result.personalInfo.gender`, type: 'string', required: false, description: 'Gender' },
    { field: `${prefix}result.personalInfo.fatherHusbandName`, type: 'string', required: false, description: "Father's/Husband's name" },
    { field: `${prefix}result.personalInfo.relation`, type: 'string', required: false, description: 'Relation type (FATHER/HUSBAND)' },
    { field: `${prefix}result.personalInfo.nationality`, type: 'string', required: false, description: 'Nationality' },
    { field: `${prefix}result.personalInfo.maritalStatus`, type: 'string', required: false, description: 'Marital status' },
    { field: `${prefix}result.personalInfo.qualification`, type: 'string', required: false, description: 'Educational qualification' },
    { field: `${prefix}result.personalInfo.mobileNumber`, type: 'string', required: false, description: 'Mobile number on record' },
    { field: `${prefix}result.personalInfo.emailId`, type: 'string', required: false, description: 'Email ID on record' },
    { field: `${prefix}result.personalInfo.pan`, type: 'string', required: false, description: 'PAN number' },
    { field: `${prefix}result.personalInfo.passport`, type: 'string', required: false, description: 'Passport number (nullable)' },
    { field: `${prefix}result.personalInfo.uan`, type: 'string', required: false, description: 'UAN on record' },
    { field: `${prefix}result.summary`, type: 'object', required: false, description: 'Summary of all verification checks' },
    { field: `${prefix}result.summary.emailParameters`, type: 'object', required: false, description: 'Summary of email verification parameters' },
    { field: `${prefix}result.summary.emailParameters.isValid`, type: 'boolean', required: false, description: 'Whether the email is valid' },
    { field: `${prefix}result.summary.emailParameters.person`, type: 'object', required: false, description: 'Person name match summary against email' },
    { field: `${prefix}result.summary.emailParameters.person.match`, type: 'boolean', required: false, description: 'Whether the person name matches' },
    { field: `${prefix}result.summary.emailParameters.person.matchScore`, type: 'float', required: false, description: 'Person match score' },
    { field: `${prefix}result.summary.emailParameters.organization`, type: 'object', required: false, description: 'Organization match summary against email' },
    { field: `${prefix}result.summary.emailParameters.organization.match`, type: 'boolean', required: false, description: 'Whether the organization matches' },
    { field: `${prefix}result.summary.emailParameters.organization.orgName`, type: 'string', required: false, description: 'Matched organization name' },
    { field: `${prefix}result.summary.emailParameters.alerts`, type: 'boolean', required: false, description: 'Whether any alerts were raised for the email' },
    { field: `${prefix}result.summary.emailValid`, type: 'boolean', required: false, description: 'Overall email validity flag' },
    { field: `${prefix}result.summary.nameLookup`, type: 'object', required: false, description: 'Summary of the name lookup result' },
    { field: `${prefix}result.summary.nameLookup.matchName`, type: 'string', required: false, description: 'Matched name' },
    { field: `${prefix}result.summary.nameLookup.isUnique`, type: 'boolean', required: false, description: 'Whether the matched name is unique' },
    { field: `${prefix}result.summary.nameLookup.isLatest`, type: 'boolean', required: false, description: 'Whether this is the latest employment record' },
    { field: `${prefix}result.summary.nameLookup.result`, type: 'boolean', required: false, description: 'Overall name lookup result' },
    { field: `${prefix}result.summary.uanLookup`, type: 'object', required: false, description: 'Summary of the UAN lookup result' },
    { field: `${prefix}result.summary.uanLookup.currentEmployer`, type: 'string', required: false, description: 'Current employer per UAN records' },
    { field: `${prefix}result.summary.uanLookup.matchScore`, type: 'float', required: false, description: 'UAN match score' },
    { field: `${prefix}result.summary.uanLookup.result`, type: 'boolean', required: false, description: 'Overall UAN lookup result' },
    { field: `${prefix}result.summary.uanLookup.uanNameMatch`, type: 'boolean', required: false, description: 'Whether the UAN name matches the input' },
    { field: `${prefix}result.summary.waiveFi`, type: 'boolean', required: false, description: 'Whether the field investigation can be waived based on this verification' },
    { field: `${prefix}result.failures`, type: 'array', required: false, description: 'Top-level failures encountered (populated when showFailures is true)' },
    { field: `${prefix}result.pdfLink`, type: 'string', required: false, description: 'Link to the PDF report (populated when pdf is true)' },
  ]
}

const EXAMPLE_RESULT = {
  email: {
    additionalInfo: {
      companyInfo: {
        orgDomainMatch: [{ domain: 'perfios.com', match: true, orgName: 'PERFIOS SOFTWARE SOLUTIONS PRIVATE LIMITED', source: 'mca, epf, gst' }],
        orgEmailMatch: [
          { companyEmail: 'omkar@perfios.com', match: false, orgName: 'PERFIOS SOFTWARE SOLUTIONS PRIVATE LIMITED', source: 'mca' },
          { companyEmail: 'ankit.s@perfios.com', match: false, orgName: 'PERFIOS SOFTWARE SOLUTIONS PRIVATE LIMITED', source: 'epf' },
        ],
        usrDirectorMatch: [{ match: false, name: '', orgName: 'PERFIOS SOFTWARE SOLUTIONS PRIVATE LIMITED', score: 0 }],
      },
      individualMatch: [{ match: false, name: 'sawrnava m', score: 0.80555555555555 }],
      spamRecord: { spamEmail: false, reportCount: 0, ipBlacklist: false },
      whoisInfo: {
        ageYear: 8.5, creationDate: '2015-02-11 09:29:49', expirationDate: '2024-02-11 09:29:49',
        updateDate: '2023-02-14 17:49:53', expired: false,
        whoisEmailDomainMatch: [], whoisEmailMatch: [], whoisIndvName: [],
        whoisOrgName: [{ match: true, orgName: 'PERFIOS SOFTWARE SOLUTIONS PRIVATE LIMITED', score: 1 }],
      },
    },
    data: { acceptAll: false, disposable: false, email: 'sawrnava.m@perfios.com', genericEmail: false, mxRecords: true, regexp: true, result: true, smtpCheck: false, webmail: false },
    result: true,
  },
  nameLookup: {
    organizationName: 'Perfios Software Solution Private Limited',
    epfHistory: [
      { totalAmount: 1189150, totalMembers: 299, formatted_wage_month: '2306', wageMonth: 'JUN-23' },
      { totalAmount: 1204150, totalMembers: 303, formatted_wage_month: '2305', wageMonth: 'MAY-23' },
    ],
    estInfo: [{ address: '1302, Orchid, Bg Kher Road Campacola Compound', contactNo: '8169584238', emailId: 'ankit.s@perfios.com', estId: 'MHBANxxxxxxxxxx' }],
    matches: [{ name: 'SWARNAVA MAITRA', confidence: 1, estId: ' MHBANxxxxxxxxxx', epfHistory: { 'JUN-23': true, 'MAY-23': true, 'APR-23': true } }],
    isNameExact: true, isEmployed: true, isRecent: true, isNameUnique: true, employeeName: 'SWARNAVA MAITRA',
  },
  uan: [
    {
      uan: '10xxxxxxxxxx',
      uanSource: 'pan',
      employer: [
        {
          name: 'Perfios Software Solution Private Limited', memberId: 'MHBANxxxxxxxxxxxxxxxxx',
          settled: null, dateOfExit: null, dateOfJoining: '2017-10-16', lastMonthYear: '', startMonthYear: '10-2017',
          employmentPeriod: null, isNameUnique: true, matchName: 'SWARNAVA MAITRA', lastMonth: '2306',
          isRecent: true, isNameExact: true, isEmployed: true, nameConfidence: 1, emplrScore: 1, uanNameMatch: true,
        },
        {
          name: 'INDUS VALLEY PARTNERS (INDIA) PVT LTD', memberId: 'DSNHPxxxxxxxxxxxxxxxxx',
          settled: null, dateOfExit: '2017-10-06', dateOfJoining: '2013-06-24', lastMonthYear: '10-2017', startMonthYear: '06-2013',
          employmentPeriod: 53, isNameUnique: false, matchName: null, lastMonth: '1710',
          isRecent: false, isNameExact: false, isEmployed: false, nameConfidence: null, emplrScore: 0.3687667184450832, uanNameMatch: true,
        },
      ],
      failures: [],
    },
  ],
  personalInfo: {
    name: 'SWARNAVA MAITRA', dateOfBirth: '1993-11-03', gender: 'M', fatherHusbandName: 'SANJEEV MAITRA',
    relation: 'FATHER', nationality: 'INDIAN', maritalStatus: 'UN-MARRIED', qualification: 'GRADUATE',
    mobileNumber: '93xxxxxxxx', emailId: 'swarnavamaitra@gmail.com', pan: 'DFKxxxx95K', passport: null, uan: '10xxxxxxxxxx',
  },
  summary: {
    emailParameters: {
      isValid: true,
      person: { match: true, matchScore: 0.80555555555555 },
      organization: { match: true, orgName: 'PERFIOS SOFTWARE SOLUTIONS PRIVATE LIMITED' },
      alerts: false,
    },
    emailValid: true,
    nameLookup: { matchName: 'SWARNAVA MAITRA', isUnique: true, isLatest: true, result: true },
    uanLookup: { currentEmployer: 'Perfios Software Solution Private Limited', matchScore: 1, result: true, uanNameMatch: true },
    waiveFi: true,
  },
  failures: [],
  pdfLink: '',
}

const DEFAULT: ApiVariant = {
  label: 'Employment verification (PAN flow)',
  request: {
    params: REQUEST_PARAMS,
    body: JSON.stringify({
      uans: ['1xxxxxxxxxx4'],
      entityId: 'U74120MH2015PTC265316',
      employerName: 'Perfios Software Solutions Private Limited',
      employeeName: 'Swarnava Maitra',
      mobile: '8xxxxxxxx6',
      emailId: 'sawrnava.m@perfios.com',
      runPanFlow: true,
      pan: 'DFKxxxx95K',
      showFailures: true,
      isLatestEmployer: true,
      pdf: true,
      consent: 'Y',
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'status-code', type: 'string', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'request_id', type: 'string', required: true, description: 'Unique id of the API request.' },
      ...responseFields(''),
      { field: 'clientData', type: 'object', required: true, description: 'Data of the user sharing consent' },
      { field: 'clientData.caseId', type: 'string', required: true, description: 'Unique case id/lead id of the user sharing consent' },
    ],
    body: JSON.stringify({
      result: EXAMPLE_RESULT,
      request_id: '1a06cb30-9dad-41f2-8a05-7cf92504263d',
      'status-code': '101',
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

export const EMPLOYMENT_ADVANCED_VARIANTS: ApiVariant[] = [DEFAULT]
export { responseFields as employmentAdvancedResponseFields }
