import type { ApiVariant } from './api-definitions'

const HEADERS_WITH_KEY = `Content-Type : "application/json"\nx-karza-key: "<<YOUR KEY HERE>>"`
const HEADERS_JSON_ONLY = `Content-Type : "application/json"`

const BASE_REQUEST_PARAMS = [
  { name: 'consent', in: 'body' as const, required: true, type: 'string' as const, enum: ['Y', 'N'], description: 'Consent is required to make the API request.' },
  { name: 'additionalData', in: 'body' as const, required: false, type: 'boolean' as const, description: 'Optional Parameter: To fetch HSN Summary of the entity and certain additional data-points' },
  { name: 'gstin', in: 'body' as const, required: true, type: 'string' as const, uppercase: true, placeholder: '27AAACR5055K1Z7', description: 'Fifteen character unique GSTIN to be authenticated', example: 'minLength: 15 maxLength: 15' },
  { name: 'clientData', in: 'body' as const, required: false, type: 'object' as const, description: 'Data of the user sharing consent' },
  { name: 'clientData.caseId', in: 'body' as const, required: false, type: 'string' as const, description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
]

const BASE_RESULT_FIELDS = [
  { field: 'result.canFlag', type: 'string', required: false, description: 'Flag to identify if an application for cancellation of GST has been filed' },
  { field: 'result.contacted', type: 'object', required: false, description: 'Contact details fetched using internal database' },
  { field: 'result.contacted.email', type: 'string', required: false, description: 'Email ID' },
  { field: 'result.contacted.mobNum', type: 'string', required: false, description: 'Mobile Number' },
  { field: 'result.contacted.name', type: 'string', required: false, description: 'Name' },
  { field: 'result.ppr', type: 'string', required: false, description: 'NA' },
  { field: 'result.cmpRt', type: 'string', required: false, description: 'Compliance rating if provided by GSP' },
  { field: 'result.rgdt', type: 'string', required: false, description: 'Registration date under GST' },
  { field: 'result.tradeNam', type: 'string', required: false, description: 'Trade Name' },
  { field: 'result.nba', type: 'array', required: false, description: 'Nature of business registered under GST' },
  { field: 'result.mbr', type: 'array', required: false, description: 'Member names if provided by GSP' },
  { field: 'result.adadr', type: 'array', required: false, description: 'Address information for additional places of business' },
  { field: 'result.adadr[].addr', type: 'string', required: false, description: 'Address' },
  { field: 'result.adadr[].ntr', type: 'string', required: false, description: 'Nature of business carried out at the address' },
  { field: 'result.adadr[].adr', type: 'string', required: false, description: 'Address' },
  { field: 'result.adadr[].em', type: 'string', required: false, description: 'Email id' },
  { field: 'result.adadr[].lastUpdatedDate', type: 'string', required: false, description: 'Last updated date of the address' },
  { field: 'result.adadr[].mb', type: 'string', required: false, description: 'Mobile number' },
  { field: 'result.pradr', type: 'object', required: false, description: 'Address information for principal place of business' },
  { field: 'result.pradr.addr', type: 'string', required: false, description: 'Address' },
  { field: 'result.pradr.ntr', type: 'string', required: false, description: 'Nature of business carried out at the address' },
  { field: 'result.pradr.adr', type: 'string', required: false, description: 'Complete Address' },
  { field: 'result.pradr.em', type: 'string', required: false, description: 'Email ID' },
  { field: 'result.pradr.lastUpdatedDate', type: 'string', required: false, description: 'Last updated date of this address' },
  { field: 'result.pradr.mb', type: 'string', required: false, description: 'Mobile Number' },
  { field: 'result.stjCd', type: 'string', required: false, description: 'State Jurisdiction Code' },
  { field: 'result.lstupdt', type: 'string', required: false, description: 'Last Updated' },
  { field: 'result.gstin', type: 'string', required: false, description: 'Given GSTIN' },
  { field: 'result.ctjCd', type: 'string', required: false, description: 'Central Jurisdiction Code' },
  { field: 'result.stj', type: 'string', required: false, description: 'State Jurisdiction' },
  { field: 'result.dty', type: 'string', required: false, description: 'Taxpayer Type' },
  { field: 'result.cxdt', type: 'string', required: false, description: 'Date of Cancellation of Registration' },
  { field: 'result.ctb', type: 'string', required: false, description: 'Constitution of Business (proprietorship, partnership, private limited company, public limited company etc)' },
  { field: 'result.sts', type: 'string', required: false, description: 'Current status of registration under GST' },
  { field: 'result.lgnm', type: 'string', required: false, description: 'Legal Name of the Business or Individual corresponding to the GSTIN' },
  { field: 'result.ctj', type: 'string', required: false, description: 'Central Jurisdiction' },
]

const ADDITIONAL_DATA_FIELDS = [
  { field: 'result.bzgddtls', type: 'array', required: false, description: 'HSN details for Goods' },
  { field: 'result.bzgddtls[].gdes', type: 'string', required: false, description: 'Description of goods' },
  { field: 'result.bzgddtls[].hsncd', type: 'string', required: false, description: 'HSN Code for goods' },
  { field: 'result.bzgddtls[].subIndustry', type: 'string', required: false, description: 'Sub-Industry' },
  { field: 'result.bzgddtls[].industry', type: 'string', required: false, description: 'Industry' },
  { field: 'result.bzsdtls', type: 'array', required: false, description: 'SAC details for services' },
  { field: 'result.bzsdtls[].saccd', type: 'string', required: false, description: 'SAC code for services' },
  { field: 'result.bzsdtls[].sdes', type: 'string', required: false, description: 'Description of services' },
  { field: 'result.aggreTurnOver', type: 'string', required: false, description: 'Aggregated annual PAN level turnover slab of the entity' },
  { field: 'result.mandatedeInvoice', type: 'string', required: false, description: 'Whether E-Invoice is mandatory for the entity - Yes or No' },
  { field: 'result.ntcrbs', type: 'string', required: false, description: 'Nature Of Core Business Activity [Manufacturer (MFT) / Trader - Retailer (TRD:TRR) / Trader - Wholesaler/Distributor (TRD:TWD) / Service Provider and Others (SPO)]' },
  { field: 'result.adhrVFlag', type: 'string', required: false, description: 'Whether Aadhaar authenticated' },
  { field: 'result.gtiFY', type: 'string', required: false, description: 'Gross total income pertaining to the financial year' },
  { field: 'result.ekycVFlag', type: 'string', required: false, description: 'Whether e-KYC verified' },
  { field: 'result.percentTaxInCash', type: 'string', required: false, description: 'Percentage of tax payment in cash' },
  { field: 'result.compDetl', type: 'boolean', required: false, description: 'Whether compliance details available' },
  { field: 'result.gti', type: 'string', required: false, description: 'Gross total income as per income-tax returns (from CBDT database)' },
  { field: 'result.aggreTurnOverFY', type: 'string', required: false, description: 'Aggregated annual PAN level turnover slab of the entity pertaining to the financial year' },
  { field: 'result.percentTaxInCashFY', type: 'string', required: false, description: 'Percentage of tax payment in cash pertaining to the financial year' },
]

const CLIENT_DATA_FIELDS = [
  { field: 'clientData', type: 'object', required: true, description: 'Data of the user sharing consent' },
  { field: 'clientData.caseId', type: 'string', required: true, description: 'Unique case id/lead id of the user sharing consent' },
]

const WITH_ADDITIONAL_DATA: ApiVariant = {
  label: 'When additionalData is true',
  request: {
    params: BASE_REQUEST_PARAMS,
    body: JSON.stringify({ consent: 'Y', additionalData: true, gstin: '27AAACR5055K1Z7', clientData: { caseId: '123456' } }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'requestId', type: 'string', required: true, description: 'Unique id of the API request.' },
      { field: 'result', type: 'object', required: true, description: 'Response object for the given inputs' },
      ...BASE_RESULT_FIELDS,
      ...ADDITIONAL_DATA_FIELDS,
      ...CLIENT_DATA_FIELDS,
    ],
    body: JSON.stringify({
      requestId: 'cdfedc5e-db9a-4ec8-8868-59deaafa2a04',
      result: {
        canFlag: 'NA',
        contacted: { email: null, mobNum: null, name: null },
        ppr: 'NA',
        cmpRt: 'NA',
        rgdt: '01/10/2017',
        tradeNam: 'ABC LIMITED',
        nba: ['Import', 'Retail Business', 'Wholesale Business', 'Supplier of Services', 'Warehouse / Depot'],
        mbr: [],
        adadr: [{
          addr: 'NA',
          ntr: 'Retail Business, Import, Supplier of Services, Wholesale Business',
          adr: 'ABC Towers, A-101, 10TH, SENAPATI BAPAT MARG, ELPHINSTONE ROAD, Maharashtra, pin: 400013',
          em: '', lastUpdatedDate: 'NA', mb: '',
        }],
        pradr: {
          addr: 'NA',
          ntr: 'Import, Retail Business, Wholesale Business, Supplier of Services',
          adr: 'TATA COURT, 101-A, 10TH, M.G. ROAD, FORT, Maharashtra, pin: 400001',
          em: '', lastUpdatedDate: 'NA', mb: '',
        },
        stjCd: 'MHCG0001',
        lstupdt: '20/11/2020',
        gstin: '27AAECP1234G1ZJ',
        ctjCd: 'VN0705',
        stj: 'FORT-701',
        dty: 'Regular',
        cxdt: '',
        ctb: 'Public Limited Company',
        sts: 'Active',
        lgnm: 'ABC LIMITED',
        ctj: 'RANGE-VII',
        bzgddtls: [
          { gdes: 'PARTS SUITABLE FOR USE SOLELY OR PRINCIPALLY WITH THE MACHINERY OF HEADINGS 8425 TO 8430', hsncd: '8431', subIndustry: 'Nuclear reactors, boilers, machinery and mechanical appliances; parts thereof.', industry: 'Machinery and Mechanical Appliances; Electrical Equipment; Parts thereof; sound Recorders and Reproducers, Television Image' },
          { gdes: 'TUBES, PIPES AND HOSES, AND FITTINGS THEREFOR (FOR EXAMPLE, JOINTS, ELBOWS, FLANGES), OF PLASTICS', hsncd: '3917', subIndustry: 'Plastics and articles thereof', industry: 'Plastics and Articles thereof; Rubber and Articles Thereof' },
          { gdes: 'OTHER FURNITURE AND PARTS THEREOF', hsncd: '9403', subIndustry: 'Furniture; bedding, mattresses, mattress supports, cushions and similar stuffed furnishings; lamps and lighting fittings,', industry: 'Miscellaneous Manufactured Articles' },
        ],
        bzsdtls: [
          { saccd: '00440076', sdes: 'INTERIOR DECORATORS/ DESIGNERS SERVICE' },
          { saccd: '00440072', sdes: 'ARCHITECTS SERVICES' },
        ],
        aggreTurnOver: 'Slab: Rs. 25 Cr. to 100 Cr. ',
        mandatedeInvoice: 'No',
        ntcrbs: 'MFT',
        adhrVFlag: 'No',
        gtiFY: '2018-2019',
        ekycVFlag: 'No',
        percentTaxInCash: 'NA',
        compDetl: true,
        gti: 'Up to Rs. 2.5 lakhs',
        aggreTurnOverFY: '2019-2020',
        percentTaxInCashFY: '',
      },
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

const WITHOUT_ADDITIONAL_DATA: ApiVariant = {
  label: 'When additionalData is false or missing',
  request: {
    params: BASE_REQUEST_PARAMS,
    body: JSON.stringify({ consent: 'Y', additionalData: false, gstin: '27AAACR5055K1Z7', clientData: { caseId: '123456' } }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request' },
      { field: 'requestId', type: 'string', required: true, description: 'Unique id of the API request' },
      { field: 'result', type: 'object', required: true, description: 'Response object for the given inputs' },
      ...BASE_RESULT_FIELDS,
      ...CLIENT_DATA_FIELDS,
    ],
    body: JSON.stringify({
      requestId: 'e17b624f-52ea-48d0-bfdb-320885d4034d',
      result: {
        canFlag: null,
        contacted: { email: '', mobNum: '', name: null },
        ppr: null,
        cmpRt: 'NA',
        rgdt: '01/07/2017',
        tradeNam: 'RELIANCE INDUSTRIES LIMITED',
        nba: ['Factory / Manufacturing', 'Retail Business', 'Input Service Distributor (ISD)', 'Bonded Warehouse', 'SEZ', 'Works Contract', 'Warehouse / Depot', 'Service Provision', 'Leasing Business', 'Office / Sale Office', 'Recipient of Goods or Services', 'Wholesale Business', 'EOU / STP / EHTP', 'Supplier of Services', 'Others', 'Export'],
        mbr: ['Nikhil Rasiklal Meswani', 'Hital Rasiklal Meswani', 'Mukesh Dhirubhai Ambani', 'Pawan Kumar Kapil', 'Madhusudana Sivaprasad Panda'],
        adadr: [{
          adr: 'IV, MAKER CHAMBERS, NARIMAN POINT, MUMBAI, Mumbai, Maharashtra, 400021',
          em: '', mb: '',
          ntr: 'Factory / Manufacturing, Retail Business, Input Service Distributor (ISD), Bonded Warehouse, SEZ, Works Contract, Warehouse / Depot',
          addr: 'NA', lastUpdatedDate: 'NA',
        }],
        pradr: {
          adr: '5, 5, TTC Industrial Area, Reliance Corporate Park, Thane Belapur Road, Ghansoli, Navi Mumbai, Thane, Maharashtra, 400701',
          em: '', mb: '',
          ntr: 'Factory / Manufacturing, Retail Business, Input Service Distributor (ISD), Bonded Warehouse, SEZ, Works Contract, Warehouse / Depot',
          addr: 'NA', lastUpdatedDate: 'NA',
        },
        stjCd: null,
        lstupdt: null,
        gstin: '27AAACR5055K1Z7',
        ctjCd: null,
        stj: 'State - Maharashtra,Zone - Thane,Division - RAIGAD,Charge - URAN_701',
        dty: 'Regular',
        cxdt: null,
        ctb: 'Public Limited Company',
        sts: 'Active',
        lgnm: 'RELIANCE INDUSTRIES LIMITED',
        ctj: 'Commissionerate - BELAPUR,Division - DIVISION IV,Range - RANGE-IV (Jurisdictional Office)',
      },
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

export const GST_VARIANTS: ApiVariant[] = [WITH_ADDITIONAL_DATA, WITHOUT_ADDITIONAL_DATA]
