import type { ApiVariant } from './api-definitions'

const HEADERS_WITH_KEY = `Content-Type : "application/json"\nx-karza-key: "<<YOUR KEY HERE>>"`
const HEADERS_JSON_ONLY = `Content-Type : "application/json"`

const RC_RESPONSE_FIELDS = [
  { field: 'blackListInfo', type: 'array', required: false, description: 'Blacklist information of the vehicle' },
  { field: 'blackListStatus', type: 'string', required: false, description: 'Blacklist status of the vehicle' },
  { field: 'bodyTypeDescription', type: 'string', required: false, description: 'Body Type of the Vehicle' },
  { field: 'chassisNumber', type: 'string', required: false, description: 'Chassis Number of the Vehicle' },
  { field: 'color', type: 'string', required: false, description: 'Registered Color of the Vehicle' },
  { field: 'cubicCapacity', type: 'string', required: false, description: 'Cubic Capacity of the Vehicle Engine' },
  { field: 'engineNumber', type: 'string', required: false, description: 'Engine Number of the vehicle' },
  { field: 'fatherName', type: 'string', required: false, description: "Father's Name of Registered Owner of the vehicle" },
  { field: 'financier', type: 'string', required: false, description: 'Name of Vehicle Financier' },
  { field: 'fitnessUpto', type: 'string', required: false, description: 'Date of Validity of Vehicle Fitness certificate' },
  { field: 'fuelDescription', type: 'string', required: false, description: 'Vehicle Fuel Type' },
  { field: 'grossVehicleWeight', type: 'string', required: false, description: 'Gross Weight of the Vehicle' },
  { field: 'insuranceCompany', type: 'string', required: false, description: 'Insurer Name of the Vehicle' },
  { field: 'insurancePolicyNumber', type: 'string', required: false, description: 'Insurance Policy Number of the Vehicle' },
  { field: 'insuranceUpto', type: 'string', required: false, description: 'Date of validity of RC Insurance' },
  { field: 'makerDescription', type: 'string', required: false, description: 'Name of Vehicle Manufacturer' },
  { field: 'makerModel', type: 'string', required: false, description: 'Vehicle Model and Make' },
  { field: 'manufacturedMonthYear', type: 'string', required: false, description: 'Month & Year of Vehicle Manufacture' },
  { field: 'nationalPermitExpiryDate', type: 'string', required: false, description: 'Expiry date of the national permit of the vehicle' },
  { field: 'nationalPermitIssuedBy', type: 'string', required: false, description: 'Name of the body which issued the National Permit for the vehicle' },
  { field: 'nationalPermitNumber', type: 'string', required: false, description: 'National Permit Number of the vehicle' },
  { field: 'nocDetails', type: 'string', required: false, description: 'Vehicle No Objection Certificate details issued by RTO' },
  { field: 'nonUseFrom', type: 'string', required: false, description: 'Date of vehicle non use from' },
  { field: 'nonUseTo', type: 'string', required: false, description: 'Date of vehicle non use to' },
  { field: 'normsDescription', type: 'string', required: false, description: 'Vehicle Pollution Norms Description' },
  { field: 'numberOfCylinders', type: 'string', required: false, description: 'Number of Cylinders' },
  { field: 'ownerName', type: 'string', required: false, description: 'Registered Name of Owner' },
  { field: 'ownerSerialNumber', type: 'string', required: false, description: 'Serial Number of Vehicle Owner' },
  { field: 'permanentAddress', type: 'string', required: false, description: 'Registered Permanent Address of the Vehicle Owner' },
  { field: 'presentAddress', type: 'string', required: false, description: 'Registered Present Address of the Owner' },
  { field: 'pucExpiryDate', type: 'string', required: false, description: 'Expiry date of PUC certificate of the vehicle' },
  { field: 'pucNumber', type: 'string', required: false, description: 'PUC Registration Number of the vehicle' },
  { field: 'rcMobileNo', type: 'string', required: false, description: 'Mobile number registered for given RC number' },
  { field: 'rcNonUseStatus', type: 'string', required: false, description: 'Vehicle RC Non use status' },
  { field: 'rcStatus', type: 'string', required: false, description: 'RC status of vehicle' },
  { field: 'registeredAt', type: 'string', required: false, description: 'Location of RTO where the vehicle was registered' },
  { field: 'registrationDate', type: 'string', required: false, description: 'Date of Registration of the Vehicle' },
  { field: 'registrationNumber', type: 'string', required: false, description: 'Registration Number of the Vehicle' },
  { field: 'seatingCapacity', type: 'string', required: false, description: 'Vehicle Passenger Seating Capacity' },
  { field: 'sleeperCapacity', type: 'string', required: false, description: 'Maximum Sleeper Capacity' },
  { field: 'standingCapacity', type: 'string', required: false, description: 'Capacity of Standing Passengers in the Vehicle' },
  { field: 'stateCd', type: 'string', required: false, description: 'State code of the vehicle' },
  { field: 'statePermitExpiryDate', type: 'string', required: false, description: 'Expiry date of the State permit of the vehicle' },
  { field: 'statePermitIssuedDate', type: 'string', required: false, description: 'Date of issue of State Permit of the vehicle' },
  { field: 'statePermitNumber', type: 'string', required: false, description: 'State Permit Number of the vehicle' },
  { field: 'statePermitType', type: 'string', required: false, description: 'Type of State Permit issued for the vehicle' },
  { field: 'statusAsOn', type: 'string', required: false, description: 'Date of RC Status Verification' },
  { field: 'stautsMessage', type: 'string', required: false, description: 'Status message of vehicle' },
  { field: 'taxPaidUpto', type: 'string', required: false, description: 'Duration till the Tax on the Vehicle has been paid (Life time / One time)' },
  { field: 'unladenWeight', type: 'string', required: false, description: 'Unladden Weight of the Vehicle' },
  { field: 'vehicleCatgory', type: 'string', required: false, description: 'Category of vehicle' },
  { field: 'vehicleClassDescription', type: 'string', required: false, description: 'Description of Vehicle Class' },
  { field: 'wheelbase', type: 'string', required: false, description: 'Wheelbase in mm of the vehicle' },
]

const RC_RESPONSE_EXAMPLE = {
  blackListInfo: [],
  blackListStatus: 'NA',
  bodyTypeDescription: 'SALOON',
  chassisNumber: 'MBJ11JV40070650241106',
  color: 'BLACK MET',
  cubicCapacity: '1998.0',
  engineNumber: '2KD9780094',
  fatherName: 'MUKUND SHUKLA',
  financier: 'NA',
  fitnessUpto: '29-12-2021',
  fuelDescription: 'DIESEL',
  grossVehicleWeight: '2290',
  insuranceCompany: 'Reliance General Insurance Co. Ltd.',
  insurancePolicyNumber: '110522123470007351',
  insuranceUpto: '21-01-2022',
  makerDescription: 'TOYOTA KIRLOSKAR MOTOR PVT LTD',
  makerModel: 'INNOVA 2.5 G WITH POWER STEER',
  manufacturedMonthYear: '11-2006',
  nationalPermitExpiryDate: null,
  nationalPermitIssuedBy: '',
  nationalPermitNumber: '',
  nocDetails: 'NA',
  nonUseFrom: null,
  nonUseTo: null,
  normsDescription: 'Not Available',
  numberOfCylinders: '4',
  ownerName: 'SAMEER M SHUKLA',
  ownerSerialNumber: '3',
  permanentAddress: 'FLAT NO 6 SATCHIDANAND CHS , PHADKE RD DOMBIVALI E OPP,HDFC BANK KALYAN, Thane -421201',
  presentAddress: 'FLAT NO 6 SATCHIDANAND CHS , PHADKE RD DOMBIVALI E OPP,HDFC BANK KALYAN, Thane -421201',
  pucExpiryDate: '22-04-2022',
  pucNumber: 'MH00500490004913',
  rcMobileNo: '',
  rcNonUseStatus: null,
  rcStatus: 'ACTIVE',
  registeredAt: 'KALYAN, Maharashtra',
  registrationDate: '30-12-2006',
  registrationNumber: 'MH04CY4545',
  seatingCapacity: '7',
  sleeperCapacity: '0',
  standingCapacity: '0',
  stateCd: null,
  statePermitExpiryDate: null,
  statePermitIssuedDate: null,
  statePermitNumber: '',
  statePermitType: null,
  statusAsOn: null,
  stautsMessage: null,
  taxPaidUpto: '31-Dec-2099',
  unladenWeight: '1630',
  vehicleCatgory: 'LMV',
  vehicleClassDescription: 'Motor Car(LMV)',
  wheelbase: '2750',
}

const DEFAULT: ApiVariant = {
  label: 'RC advanced',
  request: {
    params: [
      { name: 'consent', in: 'body', required: true, type: 'string', enum: ['Y', 'N'], description: 'Consent is required to make the API request.' },
      { name: 'registrationNumber', in: 'body', required: true, type: 'string', uppercase: true, placeholder: 'MH04CY4545', description: 'Vehicle Registration Number', example: 'MinLength: 6 MaxLength: 20' },
      { name: 'version', in: 'body', required: true, type: 'number', description: 'API version', example: 'Value must be greater than 3' },
      { name: 'partialEngine', in: 'body', required: false, type: 'string', enum: ['Y', 'N'], description: 'If Partial engine is required' },
      { name: 'clientData', in: 'body', required: false, type: 'object', description: 'Data of the user sharing consent' },
      { name: 'clientData.caseId', in: 'body', required: false, type: 'string', description: 'Unique case id/lead id of the user sharing consent', example: 'Max-length 200' },
    ],
    body: JSON.stringify({
      registrationNumber: 'MH04CY4545',
      consent: 'Y',
      partialEngine: 'Y',
      version: 3.1,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_WITH_KEY,
  },
  response: {
    fields: [
      { field: 'statusCode', type: 'integer', required: true, description: 'Internal Status Code that denotes the status of the request.' },
      { field: 'requestId', type: 'string', required: true, description: 'Unique id of the API request.' },
      { field: 'result', type: 'object', required: true, description: 'Response object for the given inputs.' },
      ...RC_RESPONSE_FIELDS.map(f => ({ ...f, field: `result.${f.field}` })),
      { field: 'clientData', type: 'object', required: true, description: 'Data of the user sharing consent' },
      { field: 'clientData.caseId', type: 'string', required: true, description: 'Unique case id/lead id of the user sharing consent' },
    ],
    body: JSON.stringify({
      requestId: 'be275edf-f9dd-4c8c-8428-b8b5290b5a5d',
      result: RC_RESPONSE_EXAMPLE,
      statusCode: 101,
      clientData: { caseId: '123456' },
    }, null, 2),
    headers: HEADERS_JSON_ONLY,
  },
}

export const RC_ADVANCED_VARIANTS: ApiVariant[] = [DEFAULT]
